apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaccine
  labels:
    app: vaccine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaccine
  template:
    metadata:
      labels:
        app: vaccine
    spec:
      containers:
        - name: vaccine
          image: skccuser20.azurecr.io/vaccine:latest
          ports:
            - containerPort: 8080
          env:
            - name: configurl
              valueFrom:
                configMapKeyRef:
                  name: apiurl
                  key: url
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5