apiVersion: apps/v1
kind: Deployment
metadata:
  name: Vaccine
  labels:
    app: Vaccine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Vaccine
  template:
    metadata:
      labels:
        app: Vaccine
    spec:
      containers:
        - name: Vaccine
          image: username/Vaccine:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5